
name: Terraform Deployment dev

on:
  push:
    branches:
      - main

# Required for GitHub OIDC
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::684160548236:role/sabo1166
          aws-region: us-east-1

      # Verify AWS identity
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

